/**
 * Guards the authentication boundary at the point it is actually decided: the generated routes.
 *
 * An earlier middleware skipped authentication for any GET path *containing* '/url/' or '/agent',
 * so a protected route addressed as /connections/url/ ran unauthenticated. Authentication is now
 * per-route and pattern-matched, which makes that class of bypass unrepresentable -- but only for
 * as long as every route carries the middleware. A controller added without a @Security decorator
 * silently becomes public, which is exactly what this asserts against.
 *
 * routes.ts is generated by `yarn tsoa`, so this reads the generated file rather than the sources.
 */
import { readFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const routesPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'routes', 'routes.ts')
const routes = readFileSync(routesPath, 'utf8').split('\n')

// The only endpoints a caller may reach with no credential. Both are unavoidably public: a wallet
// resolves an invitation before any connection exists, and a token endpoint cannot require the
// token it issues. Adding to this list is a security decision, not a formality.
const PUBLIC_ROUTES = ['GET /didcomm/url/:invitationId', 'POST /v1/orgs/:orgId/token']

type Registration = { route: string; middleware: string }

function registrations(): Registration[] {
  const found: Registration[] = []
  routes.forEach((line, index) => {
    const match = line.match(/^\s+app\.(get|post|put|delete|patch)\('([^']+)'/)
    if (!match) return
    found.push({
      route: `${match[1].toUpperCase()} ${match[2]}`,
      middleware: routes[index + 1] ?? '',
    })
  })
  return found
}

describe('generated route authentication', () => {
  const registered = registrations()

  it('finds the generated routes', () => {
    expect(registered.length).toBeGreaterThan(100)
  })

  it('puts every route behind authenticateMiddleware', () => {
    const unguarded = registered.filter(({ middleware }) => !middleware.includes('authenticateMiddleware'))
    expect(unguarded.map(({ route }) => route)).toEqual([])
  })

  it('skips authentication on exactly the routes that are meant to be public', () => {
    const skipping = registered
      .filter(({ middleware }) => middleware.includes('"skip"'))
      .map(({ route }) => route)
      .sort()
    expect(skipping).toEqual([...PUBLIC_ROUTES].sort())
  })

  it('leaves no route reachable by putting "url" or "agent" in a path segment', () => {
    // The bypassed paths from the assessment. None of them is a registered pattern, so Express
    // cannot route them to a handler regardless of what any middleware decides.
    const bypassAttempts = [
      'GET /connections/url/',
      'GET /credentials/url/',
      'GET /proofs/url/',
      'GET /schemas/url/',
      'GET /dids/url/',
      'GET /connections/agent/',
      'GET /multi-tenancy/url/',
    ]
    const patterns = registered.map(({ route }) => route)
    expect(patterns.filter((pattern) => bypassAttempts.includes(pattern))).toEqual([])
  })
})
